### ISSUE TITLE
Error with Go 1.9.1

### ISSUE THREAD

**Issue by siegesmund** [jbowtie/gokogiri#4]
Getting this error after upgrading to go 1.9.1, Mac OS High Sierra.

`github.com/jbowtie/gokogiri/help
../../jbowtie/gokogiri/help/help.go:6:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^~~~~~~~~~~~~~~
1 error generated.
github.com/jbowtie/gokogiri/xpath
../../jbowtie/gokogiri/xpath/expression.go:4:10: fatal error: 'libxml/xpath.h' file not found
#include <libxml/xpath.h>
         ^~~~~~~~~~~~~~~~
1 error generated.`

Fails with this error on build, and on go get ...

**Comment by jbowtie** [comment]
The documentation probably needs to be clearer here -- you need the headers (and libs) for libxml2 installed before gokogiri will build.

I don't use MacOS personally so don't know how you go about installing and/or adding them to your include path.  If someone wants to document that I'd be happy to add the details to the README,

**Comment by siegesmund** [comment]
Hmmm. So, MacOS ships with libxml2. You can also install it via Homebrew, but either way, it's present.  I've been using Gokogiri for about 6 months, and this is the first time this has happened... This seemed to coincide with upgrading to 1.9.1. Strange...

**Comment by jbowtie** [comment]
Nothing obvious in the release notes for 1.9 and 1.9.1 -- it's possible some of the tooling changes has changed a cgo default.

You could try explicitly setting CGO_CFLAGS to see if that addresses the issue with locating the headers, or setting a '#cgo pkg-config: xml2' directive.  But at this point I'm speculating since I don't have a Mac to reproduce the issue.

**Comment by siegesmund** [comment]
I was able to fix this. It was not a problem with Gokogiri, but with links that seem to have been corrupted. Recreating them allowed the Go compiler to find libxml again. Thanks for helping me narrow the problem, and thanks for keeping this repo up to date!
